// Code generated by "stringer -type=MagnitudeType"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[YOCTO-0]
	_ = x[ZEPTO-1]
	_ = x[ATTO-2]
	_ = x[FEMTO-3]
	_ = x[PICO-4]
	_ = x[NANO-5]
	_ = x[MICRO-6]
	_ = x[MILLI-7]
	_ = x[IU-8]
	_ = x[KILO-9]
	_ = x[MEGA-10]
	_ = x[GIGA-11]
	_ = x[TERA-12]
	_ = x[PETA-13]
}

const _MagnitudeType_name = "YOCTOZEPTOATTOFEMTOPICONANOMICROMILLIIUKILOMEGAGIGATERAPETA"

var _MagnitudeType_index = [...]uint8{0, 5, 10, 14, 19, 23, 27, 32, 37, 39, 43, 47, 51, 55, 59}

func (i MagnitudeType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MagnitudeType_index)-1 {
		return "MagnitudeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MagnitudeType_name[_MagnitudeType_index[idx]:_MagnitudeType_index[idx+1]]
}
