// Code generated by "stringer -type=UnitType"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[V-0]
	_ = x[A-1]
	_ = x[VV-2]
	_ = x[AA-3]
	_ = x[OU-4]
	_ = x[W-5]
	_ = x[SQRT_V-6]
	_ = x[SQRT_A-7]
	_ = x[INTEGRAL_V-8]
	_ = x[INTEGRAL_A-9]
	_ = x[DT_V-10]
	_ = x[DT_A-11]
	_ = x[DT_DIV-12]
	_ = x[Hz-13]
	_ = x[S-14]
	_ = x[SA-15]
	_ = x[PTS-16]
	_ = x[NULL-17]
	_ = x[DB-18]
	_ = x[DBV-19]
	_ = x[DBA-20]
	_ = x[VPP-21]
	_ = x[VDC-22]
	_ = x[DBM-23]
}

const _UnitType_name = "VAVVAAOUWSQRT_VSQRT_AINTEGRAL_VINTEGRAL_ADT_VDT_ADT_DIVHzSSAPTSNULLDBDBVDBAVPPVDCDBM"

var _UnitType_index = [...]uint8{0, 1, 2, 4, 6, 8, 9, 15, 21, 31, 41, 45, 49, 55, 57, 58, 60, 63, 67, 69, 72, 75, 78, 81, 84}

func (i UnitType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UnitType_index)-1 {
		return "UnitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnitType_name[_UnitType_index[idx]:_UnitType_index[idx+1]]
}
